ament_prepend_unique_value GAZEBO_MODEL_PATH "/husarion_ws/install/erc2025_remote_sim/share/erc2025_remote_sim/models"
ament_prepend_unique_value GZ_SIM_RESOURCE_PATH "/husarion_ws/install/erc2025_remote_sim/share/erc2025_remote_sim/models"
ament_prepend_unique_value IGN_GAZEBO_RESOURCE_PATH "/husarion_ws/install/erc2025_remote_sim/share/erc2025_remote_sim/models"
